create table pitangacos.products(
	productID int not null AUTO_INCREMENT,
    category varchar(100) not null,
    `name` varchar(200) not null,
    `range` varchar(100) not null,
    content varchar(100) not null,
    imageURL varchar(200) not null,
    price decimal(6,2) not null,
    currentPrice decimal(6,2), 
    description varchar(1000),
    details varchar(500),
    `active` bool NOT NULL DEFAULT 1,
	
	primary key (productID)
);

insert into pitangacos.products (category,`name`,`range`, content, imageURL, price,currentPrice, description, details)
values  ("makeup","Corretivo Alta Cobertura Aquarela", "AQUARELA", "8ml", "images/corretivo_natura.jpg",32.90, 22.90,"O Corretivo Alta Cobertura Aquarela traz mais, mais e mais cobertura, camufla olheiras e imperfeições com efeito levemente luminoso. Sua textura é cremosa, livre de óleos, e ainda tem secagem rápida com mais duração e acabamento natural.", "Benefícios:<br> Mais alta cobertura com efeito levemente luminoso.<br>Camufla olheiras e imperfeições.<br>Textura cremosa com secagem rápida.<br> Longa duração."),
		("makeup","Base Nude Me Sérum FPS18", "UNA", "30ml", "images/base nude.jpg", 190.90, 144.90, "A Nude Me Base Sérum FPS 18 Una é a opção certa, já que nem toda base pode ser usada diariamente por causa da sua textura – que pode pesar na pele. Leve, fluida e aquosa, a Nude Me é indicada para todos os tipos de pele e pode ser usada todos os dias. Com a Tecnologia Oxygen, ela não prejudica a saúde do rosto, já que essa inovação possibilita que a pele respire tanto quanto se estivesse sem o produto. Seca em tempo ideal, e deixa um acabamento perfeito: nem matte extremo nem oleoso. Atende desde as pessoas que procuram uma base confortável – que cobre imperfeições sem pesar – até quem prefere alta cobertura. Além disso, é fácil de dosar com seu aplicador conta-gotas.","Benefícios: <br> Textura ultrafina.<br> Acabamento natural.<br> Permite que a pele respire.<br> Dura até 24 h.<br> Imediatamente: cobertura, uniformidade, vitalidade e acabamento natural.<br> Após 14 dias: recupera a radiância da pele e combate sinais de estresse.<br> Após 28 dias: melhora a oxigenação da pele e aumenta a produção de energia."),
        ("makeup", "Delineador Color & Precisão Aquarela", "AQUARELA", "3.5ml", "images/delineador.jpg", 29.90,19.90, "Com o Delineador Color & Precisão Aquarela, você pode soltar a imaginação e apostar em diferentes tipos de traços, como o gatinho, geométrico, invertido ou qualquer outro que quiser.", "Benefícios:<br> Cor intensa.<br> Traço fino e preciso.<br> Fácil aplicação."),
        ("makeup", "Batom Líquido Matte Faces", "FACES", "3.5ml", "images/batom_matte.jpg", 25.90,19.90, "O Batom Líquido Matte Faces é mara! Com cobertura cover-up, ele é perfeito para você experimentar e inventar. Quanto mais você passa, mais intenso ele fica. Tá na boca, tá na bolsa, tá na mão!","Benefícios:<br> Acabamento matte.<br> Cores ousadas e vibrantes.<br> Fácil aplicação."),
        ("perfume", "Kaiak Pulso", "KAIAK", "100ml", "images/kaiak-pulso.jpg", 121.90, 121.90, "Vibrante, Kaiak Pulso combina ervas com notas de lima. Uma fragrância que move os homens e exala adrenalina. Ideal para homens que não gostam de ficar parados. \n A busca por viver intensamente traz a essência do que é Kaiak. Os desafios são atrativos para homens que não possuem medo de se aventurar.\n Sentindo o movimento das ondas seu corpo absorve a energia do mar. Guiando a bike a sensação de comando e segurança é libertadora. Enquanto aumenta a velocidade da corrida você sente seu coração ganhar um ritmo envolvente. É uma mistura de emoções que te movem. É pulsante.\n Kaiak Pulso possui uma saída que é uma explosão de frescor, ressaltada pelo contraste do corpo floral. O fundo é uma rica combinação de madeiras como musc, tonka e incenso. Fragrância totalmente inspirada na sua energia.","Caminho Olfativo: <br> Topo: Mandarina, Grapefruit, Lima.<br> Corpo: Ozônico, Rosa, Muguet.<br> Fundo: Musc, Vetiver, Cedro."),
        ("perfume", "Luna Intenso", "LUNA", "50ml", "images/luna-intenso.jpg",139.90, 99.90, "Em uma versão mais intensa, o Chipre tão característico de Luna conta com uma dose generosa do mais potente e puro patchouli combinada às notas gourmand da vanila, trazendo identidade e sensualidade ao primeiro deo parfum da marca, com uma seleção única de florais femininos e notas cremosas aveludadas de pêssego. Para mulheres que têm sensualidade à flor da pele.","Caminho Olfativo:<br> Chipre"),
        ("perfume", "Humor Próprio", "HUMOR", "75ml", "images/humor-proprio.jpg", 104.90,79.90, "Humor é um jeito de olhar a vida. Porque a graça é maior quando a gente compartilha e se permite rir de si mesma. Humor Próprio é uma fragrância adocicada e cheia de personalidade, com o colorido e a alegria da cereja em calda, mesclada ao encantamento das notas florais em um fundo ambarado superadocicado. É uma mistura de personalidade e cheia de irreverência, afinal, uma boa dose de humor próprio não faz mal a ninguém!", "Caminho Olfativo:<br> Topo: Maçã, Morango, Cereja.<br> Corpo: Rosa, Jasmim, Muguet.<br> Fundo: Musc, Vanila, Cedro."),
        ("dailycare","Creme Desodorante Nutritivo Manga Rosa e Água de Coco", "TODODIA", "400ml", "images/creme-mangarosa-aguacoco.jpg", 46.90,  46.90, "Tudo muda quando a gente descobre que tem uma energia pulsando tão forte quanto o verão. Mas este é um verão diferente. É um verão que começou dentro da gente. O Desodorante Hidratante Corporal Tododia Manga Rosa e Água de Coco conta com fragrância refrescante que combina o frutal da manga rosa com a leveza da água de coco. Além disso, possui os benefícios dos desodorantes hidratantes de Tododia que você já conhece. Aproveite um verão mais intenso com a refrescância que a estação mais quente do ano pede.","Benefícios:<br> Nutrição prebiótica: se adapta às mudanças da sua pele;<br> Textura ultrarrefrescante, acalma a pele e alivia a sensação de calor;<br> Fórmula sorbet: toque geladinho que refresca a pele;<br> Rápida absorção com formação de camada protetora na pele."),
        ("dailycare", "Kit Tododia Sabonete em Barra Algodão", "TODODIA", "3 caixas com 5 unidades de 90g cada", "images/sabonete-algodao.jpg", 59.70, 47.70, "O sabonete em barra Tododia Algodão promove agradável sensação enquanto limpa e deixa a pele macia e sedosa. Sua fórmula suave evita o ressecamento e prepara a pele para receber a combinação nutritiva duradoura de nossos hidratantes.", "Benefícios:<br> Não resseca a pele;<br> Hidrata suavemente;<br> Sensação de pele macia e sedosa."),
        ("dailycare", "Néctar Hidratante para Mãos Maracujá", "EKOS", "75g", "images/hidratanteMaos-maracuja.jpg", 37.50,19.90, "Com óleo de maracujá este néctar hidratante para mãos, de textura leve, promove hidratação imediata e prolongada das mãos. Com rápida absorção na pele, deixa suas mãos macias e delicadamente perfumadas com as notas frescas de maracujá. Ideal para usar ao longo do dia.","Benefícios:<br> O óleo de maracujá, com alta concentração de ácidos graxos essenciais, hidrata e acalma a pele, suavizando agressões externas."),
        ("dailycare","Refil Shampoo Patauá", "EKOS", "300ml", "images/shampoo-refil-pataua.jpg", 22.60,17.90, "Ideal para cabelos finos e fragilizados, com crescimento lento e que quebram facilmente, o Shampoo Ekos Patauá contém o puro óleo de Patauá, com espuma cremosa e abundante. A versão refil é econônica e sustentável.","Benefícios:<br> Prepara o couro cabeludo e fios para o tratamento de fortalecimento.<br> Remove suavemente as impurezas.<br> Espuma cremosa e abundante."),
        ("dailycare", "Creme de Pentear Brilho Intenso Cabelos Cacheados", "LUMINA", "300ml", "images/cremePentear-cabelosCacheados.jpg", 37.80,26.40, "O Creme de Pentear Brilho Intenso para Cabelos Cacheados Lumina faz parte de um completo Sistema de Tratamento, que realça o brilho dos fios, controla o frizz, hidrata intensamente e define os cachos por 24 horas, desembaraçando-os desde a lavagem. Ele também conta com a inédita Biotecnologia Pró-teia, responsável por preencher os fios de dentro para fora, na medida de cada dano. Além disso, o creme traz em sua fórmula o Ativo Hidradefinição, que define os fios cacheados e crespos, tem efeito memória de longa duração e garante aos cabelos movimento e ação antifrizz.","Benefícios:<br> Cabelos hidratados imediatamente.<br> Cachos definidos por 24 horas.<br> Brilho intenso.<br> 3x menos frizz."),
        ("beard", "Gel de Limpeza", "HOMEM", "115g", "images/gel-limpeza-facial.jpg", 42.50,19.50, "O Gel de Limpeza Facial Natura Homem limpa, controla a oleosidade da pele e desobstrui os poros. Ideal para o homem que se cuida.","Benefícios:<br> A betaína de cupuaçu em sua composição controla a oleosidade;<br> Desobstriu os poros<br> Sabonete líquido facial em gel."),
        ("beard", "Creme de Barbear", "HOMEM", "75g", "images/creme-barbear.jpg", 33.90,25.90, "O Creme de Barbear Natura Homem facilita o deslizar da lâmina e acalma a pele. Também garante hidratação por até 8 horas. Ideal para o homem que se cuida","Benefícios:<br> Não resseca a pele;<br> Proporciona o alto deslize da lâmina;<br> O óleo de copaíba na fórmula acalma a pele<br> Hidrata por até 8 horas.");

